Table fct_job_ads {
    job_id INTEGER [pk]
    job_details_id INTEGER [not null]
    employer_id INTEGER [not null]
    auxilliary_attributes_id INTEGER [not null]
    number_vacancies INTEGER [not null]
    relevance FLOAT [not null]
    publication_date_id TIMESTAMP [not null]
    application_deadline_id TIMESTAMP
}

Table dim_date {
    date_id INTEGER [pk]
    date DATE [not null]
    year INTEGER [not null]
    month INTEGER [not null]
    day INTEGER [not null]
    quarter INTEGER [not null]
    week_of_year INTEGER [not null]
    day_of_week INTEGER [not null]
}

Table dim_job_details {
    job_details_id INTEGER [pk]
    headline VARCHAR [not null]
    description VARCHAR
    description_html_formatted VARCHAR
    employment_type VARCHAR
    duration VARCHAR
    salary_type VARCHAR
    scope_of_work_min DECIMAL
    scope_of_work_max DECIMAL
}

Table dim_employer {
    employer_id INTEGER [pk]
    employer_name VARCHAR [not null]
    employer_workplace VARCHAR
    employer_organization_number VARCHAR
    workplace_street_address VARCHAR
    workplace_region VARCHAR
    workplace_postcode VARCHAR
    workplace_city VARCHAR
    workplace_country VARCHAR
    employer_url VARCHAR
}

Table dim_auxilliary_attributes {
    auxilliary_attributes_id INTEGER [pk]
    experience_required BOOLEAN
    driver_license BOOLEAN
    access_to_own_car BOOLEAN
    webpage_url VARCHAR
}

Ref: fct_job_ads.job_details_id - dim_job_details.job_details_id
Ref: fct_job_ads.employer_id > dim_employer.employer_id
Ref: fct_job_ads.auxilliary_attributes_id - dim_auxilliary_attributes.auxilliary_attributes_id
Ref: dim_date.date_id < fct_job_ads.publication_date_id
Ref: dim_date.date_id < fct_job_ads.application_deadline_id