sources:
    - name: job_ads
      schema: staging
      tables: 
        - name: stg_job_ads
          identifier: stg_job_ads
          meta:
            dagster:
              asset_key: ["dlt_project_leader_stg_job_ads"]