models:
  - name: dim_employer
    columns:
      - name: employer_id
        data_tests:
          - unique
          - not_null
      - name: employer_name
        data_tests:
          - not_null
      - name: employer_workplace
      - name: employer_organization_number
      - name: workplace_street_address
      - name: workplace_region
      - name: workplace_postcode
      - name: workplace_city
      - name: workplace_country
      - name: employer_url

  - name: dim_job_details
    columns:
      - name: job_details_id
        data_tests:
          - unique
          - not_null
      - name: headline
        data_tests:
          - not_null
      - name: description
      - name: description_html_formatted
      - name: employment_type
      - name: duration
      - name: salary_type
      - name: scope_of_work_min
      - name: scope_of_work_max

  - name: dim_auxiliary_attributes
    columns:
      - name: auxilliary_attributes_id
        data_tests:
          - unique
          - not_null
      - name: experience_required
      - name: driver_license
      - name: access_to_own_car
      - name: webpage_url

  - name: dim_date
    columns:
      - name: date_id
        data_tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_increasing
      - name: date
        data_tests:
          - not_null
      - name: year
        data_tests:
          - not_null
      - name: month
        data_tests:
          - not_null
      - name: day
        data_tests:
          - not_null
      - name: quarter
        data_tests:
          - not_null
      - name: week_of_year
        data_tests:
          - not_null
      - name: day_of_week
        data_tests:
          - not_null

  - name: fct_job_ads
    columns:
      - name: job_id
        data_tests:
          - unique
          - not_null
      - name: job_details_id
        data_tests:
          - not_null
          - relationship:
              to: ref('dim_job_details')
              field: job_details_id
      - name: employer_id
        data_tests:
          - not_null
          - relationship:
              to: ref('dim_employer')
              field: employer_id
      - name: auxilliary_attributes_id
        data_tests:
          - not_null
          - relationship:
              to: ref('dim_auxiliary_attributes')
              field: auxilliary_attributes_id
      - name: number_vacancies
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer
      - name: relevance
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1
      - name: publication_date_id
        data_tests:
          - not_null
      - name: application_deadline_id
        data_tests:
          - not_null
