models:
  - name: dim_employer
    description: "Dimension table containing employer data such as name, address, etc"
    columns:
      - name: employer_id
        description: "Unique identifier for each employer"
        data_tests:
          - unique
          - not_null
      - name: employer_name
        description: "Name of the employer"
        data_tests:
          - not_null
      - name: employer_workplace
        description: "Workplace name of the employer"
        data_tests:
          - not_null
      - name: employer_organization_number
        description: "Organization number of the employer"
        data_tests:
          - not_null
      - name: workplace_street_address
        description: "Street address of the workplace"
        data_tests:
          - not_null
      - name: workplace_region
        description: "Region of the workplace"
        data_tests:
          - not_null
      - name: workplace_postcode
        description: "Postcode of the workplace"
        data_tests:
          - not_null
      - name: workplace_city
        description: "The city where the employer is located"
        data_tests:
          - not_null
      - name: workplace_country
        description: "Country where the workplace is located"
        data_tests:
          - not_null
      - name: employer_url
        description: "URL of the employer's website"
        data_tests:
          - not_null


  - name: dim_job_details
    description: "Dimension table containing details about each ad such as job titles, description, duration, etc"
    columns:
      - name: job_details_id
        description: "Unique identifier for each job detail"
        data_tests:
          - not_null
          - unique
      - name: headline
        description: "Headline of the job ad"
        data_tests:
          - not_null
      - name: job_description
        description: "The text description of the job ad"
        data_tests:
          - not_null
      - name: description_html_formatted
        description: "The HTML formatted description of the job ad"
        data_tests:
          - not_null
      - name: employment_type
        description: "The type of employment (e.g., full-time, part-time)"
        data_tests:
          - not_null
      - name: duration
        description: "The duration of the job (e.g., permanent, temporary)"
        data_tests:
          - not_null
      - name: salary_type
        description: "The type of salary (e.g., fixed, hourly)"
        data_tests:
          - not_null
      - name: scope_of_work_min
        description: "The minimum scope of work (e.g., hours per week)"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
      - name: scope_of_work_max
        description: "The maximum scope of work (e.g., hours per week)"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number

  - name: dim_auxiliary_attributes
    description: "Dimension table containing details about auxiliary attributes such as drivers license, experience required, access to a car, etc"
    columns:
      - name: auxiliary_attributes_id
        description: "Unique identifier for each auxiliary attribute"
        data_tests:
          - unique
          - not_null
      - name: experience_required
        description: "Whether experience is required for the job"
        data_tests:
          - not_null
      - name: driving_license
        description: "Whether a driving license is required for the job"
        data_tests:
          - not_null
      - name: access_to_own_car
        description: "Whether access to a car is required for the job"
        data_tests:
          - not_null
      - name: webpage_url
        description: "The URL for more information about the job"
        data_tests:
          - not_null

  - name: dim_date
    description: "Dimension table containing details about dates in the job ads"
    columns:
      - name: date_id
        description: "Unique identifier for each date"
        data_tests:
          - unique
          - not_null
      - name: date
        description: "The actual date."
        data_tests:
          - not_null
      - name: year
        description: "The year part of the date."
        data_tests:
          - not_null
      - name: month
        description: "The month part of the date."
        data_tests:
          - not_null
      - name: day
        description: "The day part of the date."
        data_tests:
          - not_null
      - name: quarter
        description: "The quarter part of the date."
        data_tests:
          - not_null
      - name: week_of_year
        description: "The week of the year part of the date."
        data_tests:
          - not_null
      - name: day_of_week
        description: "The day of the week part of the date."
        data_tests:
          - not_null

  - name: fct_job_ads
    description: "Fact table containing information about job ads related to job details, employer and auxiliary attributes"
    columns:
      - name: job_details_id
        description: "Foreign key linking to the dim_job_details table"
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_job_details')
              field: job_details_id
      - name: employer_id
        description: "Foreign key linking to the dim_employer table"
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_employer')
              field: employer_id
      - name: auxiliary_attributes_id
        description: "Foreign key linking to the dim_auxiliary_attributes table"
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_auxiliary_attributes')
              field: auxiliary_attributes_id
      - name: number_vacancies
        description: "The number of vacancies availible for the job ad"
        data_tests:
          - not_null
          - dbt_expectations.expect_column_max_to_be_between:
              min_value: 1
              max_value: 20
              config:
                severity: warn
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
      - name: relevance
        description: "Relevance of the job ad"
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: float
      - name: publication_date_id
        description: "Date for publication of an ad"
      - name: application_deadline_id
        description: "Date for application deadline of an ad"

  - name: mart_job_listings
    description: "Mart table containing curated job listings with details about job ads, employer, and auxiliary attributes. This table is used for reporting and analysis."
    columns:
      - name: headline
        description: "The headline of the job ad"
      - name: number_vacancies
        description: "The number of vacancies available for the job ad"
      - name: salary_type
        description: "The salary type for the job ad"
      - name: relevance
        description: "The relevance score of the job ad, ranging from 0 to 1"
      - name: employer_name
        description: "The name of the employer"
      - name: workplace_city
        description: "The city where the employer is located"
      - name: description
        description: "The plain text description of the job ad"
      - name: description_html_formatted
        description: "The HTML formatted description of the job ad"
      - name: duration
        description: "The duration of the job (e.g., full-time, part-time)"
      - name: scope_of_work_min
        description: "The minimum scope of work (e.g., hours per week)"
      - name: scope_of_work_max
        description: "The maximum scope of work (e.g., hours per week)"
      - name: publication_date_id
        description: "The ID of the publication date (foreign key from dim_date)"
      - name: application_deadline_id
        description: "The ID of the application deadline date (foreign key from dim_date)"
      - name: webpage_url
        description: "The URL to the webpage with more information about the job ad"
