models:
  - name: dim_employer
    description: "Dimension table containing employer data such as name, address, etc"
    columns:
      - name: employer_id
        description: "Unique identifier for each employer"
        data_tests:
          - unique
          - not_null

      - name: workplace_city
        description: "The city where the employer is located"
        data_tests:
          - not_null

  - name: dim_job_details
    description: "Dimension table containing details about each ad such as job titles, description, duration, etc"
    columns:
      - name: job_details_id
        description: "Unique identifier for each job detail"
        data_tests:
          - not_null
          - unique
      - name: headline
        description: "Headline of the job ad"
        data_tests:
          - not_null

  - name: dim_auxiliary_attributes
    description: "Dimension table containing details about auxiliary attributes such as drivers license, experience required, etc"
    columns:
      - name: auxiliary_attributes_id
        description: "Unique identifier for each auxiliary attribute"
        data_tests:
          - unique
          - not_null
  - name: dim_date
    description: "Dimension table containing details about dates in the job ads"
    columns:
      - name: date_id
        description: "Unique identifier for each date"
        data_tests:
          - unique
          - not_null

  - name: fct_job_ads
    description: "Fact table containing information about job ads related to job details, employer and auxiliary attributes"
    columns:
      - name: job_details_id
        description: "Foreign key linking to the dim_job_details table"
        data_tests:
          - relationships:
              to: ref('dim_job_details')
              field: job_details_id
      - name: employer_id
        description: "Foreign key linking to the dim_employer table"
        data_tests:
          - relationships:
              to: ref('dim_employer')
              field: employer_id
      - name: auxiliary_attributes_id
        description: "Foreign key linking to the dim_auxiliary_attributes table"
        data_tests:
          - relationships:
              to: ref('dim_auxiliary_attributes')
              field: auxiliary_attributes_id
      - name: relevance
        description: "Relevance of the job ad"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0  
              max_value: 1 

          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: float
      - name: number_vacancies
        description: "The number of vacancies availible for the job ad"
        data_tests: 
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 1
              max_value: 20
          
          - dbt_expectations.expect_column_max_to_be_between:
              min_value: 1
              max_value: 20
              config:
                severity: warn

          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
