models:
  - name: dim_employer
    columns:
      - name: employer_id
        tests:
          - unique
          - not_null
      - name: workplace_city
        tests:
          - not_null
      - name: workplace_street_address
        tests:
          - not_null
      - name: workplace_region
        tests:
          - not_null
      - name: workplace_postcode
        tests:
          - not_null
      - name: employer_url
        tests:
          - not_null

  - name: dim_job_details
    columns:
      - name: job_details_id
        tests:
          - unique
          - not_null
      - name: headline
        tests:
          - not_null
      - name: description
        tests:
          - not_null
      - name: employment_type
        tests:
          - not_null

  - name: dim_auxiliary_attributes
    columns:
      - name: auxiliary_attributes_id
        tests:
          - unique
          - not_null

  - name: dim_date
    columns:
      - name: date_id
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_increasing

  - name: fct_job_ads
    columns:
      - name: job_details_id
        tests:
          - relationship:
              to: ref('dim_job_details')
              field: job_details_id
      - name: employer_id
        tests:
          - relationship:
              to: ref('dim_employer')
              field: employer_id
      - name: auxiliary_attributes_id
        tests:
          - relationship:
              to: ref('dim_auxiliary_attributes')
              field: auxiliary_attributes_id
      - name: publication_date_id
        tests:
          - not_null
      - name: application_deadline_id
        tests:
          - not_null
      - name: relevance
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: float
      - name: number_vacancies
        tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 1
              max_value: 20
          - dbt_expectations.expect_column_max_to_be_between:
              min_value: 1
              max_value: 20
              config:
                severity: warn
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number

  - name: mart_job_listings
    columns:
      - name: headline
        tests:
          - not_null
      - name: employer_name
        tests:
          - not_null
      - name: workplace_city
        tests:
          - not_null
      - name: number_vacancies
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
      - name: relevance
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1

  - name: src_auxiliary_attributes
    columns:
      - name: id
        tests:
          - not_null
      - name: employer_name
        tests:
          - not_null

  - name: src_employer
    columns:
      - name: id
        tests:
          - not_null
      - name: employer_name
        tests:
          - not_null
      - name: workplace_city
        tests:
          - not_null

  - name: src_job_ads
    columns:
      - name: id
        tests:
          - not_null
      - name: number_vacancies
        tests:
          - not_null
      - name: relevance
        tests:
          - not_null

  - name: src_job_details
    columns:
      - name: id
        tests:
          - not_null
      - name: headline
        tests:
          - not_null
      - name: description
        tests:
          - not_null
      - name: employment_type
        tests:
          - not_null
