models:
  - name: dim_employer
    columns:
      - name: employer_id
        data_tests:
          - unique
          - not_null

      - name: workplace_city
        data_tests:
          - not_null

  - name: dim_job_details
    columns:
      - name: job_details_id
        data_tests:
          - not_null
          - unique
      - name: headline
        data_tests:
          - not_null

  - name: dim_auxiliary_attributes
    columns:
      - name: auxiliary_attributes_id
        data_tests:
          - unique
          - not_null
  - name: dim_date
    columns:
      - name: date_id
        data_tests:
          - unique
          - not_null

  - name: fct_job_ads
    columns:
      - name: job_details_id
        data_tests:
          - relationships:
              to: ref('dim_job_details')
              field: job_details_id
      - name: employer_id
        data_tests:
          - relationships:
              to: ref('dim_employer')
              field: employer_id
      - name: auxiliary_attributes_id
        data_tests:
          - relationships:
              to: ref('dim_auxiliary_attributes')
              field: auxiliary_attributes_id
      - name: relevance
        data_tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0  
              max_value: 1 

          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: float
      - name: number_vacancies
        data_tests: 
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 1
              max_value: 20
          
          - dbt_expectations.expect_column_max_to_be_between:
              min_value: 1
              max_value: 20
              config:
                severity: warn

          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
